// <auto-generated />
using System;
using Be_e_learning.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Be_e_learning.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240412150947_UPDATE2")]
    partial class UPDATE2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Be_e_learning.Model.ChuongKhoaHoc", b =>
                {
                    b.Property<string>("maCh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maKh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tenChuong")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maCh");

                    b.HasIndex("maKh");

                    b.ToTable("ChuongKhoaHoc");
                });

            modelBuilder.Entity("Be_e_learning.Model.DanhMuc", b =>
                {
                    b.Property<string>("maDm")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tenDm")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maDm");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("Be_e_learning.Model.GiangVien", b =>
                {
                    b.Property<string>("maGv")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("maNg")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ngaySinh")
                        .HasColumnType("date");

                    b.Property<string>("phai")
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("sdt")
                        .HasMaxLength(11)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("tenGv")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maGv");

                    b.HasIndex("maNg");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("Be_e_learning.Model.KhoaHoc", b =>
                {
                    b.Property<string>("maKh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("gia")
                        .HasColumnType("real");

                    b.Property<string>("gioiThieu")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("hinh")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ketQuaDatDuoc")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("maDm")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maGv")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tenKh")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("trangThai")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maKh");

                    b.HasIndex("maDm");

                    b.HasIndex("maGv");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("Be_e_learning.Model.LoaiNoiDung", b =>
                {
                    b.Property<string>("maLoaiNd")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tenLoai")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maLoaiNd");

                    b.ToTable("LoaiNoiDung");
                });

            modelBuilder.Entity("Be_e_learning.Model.NguoiDung", b =>
                {
                    b.Property<string>("maNg")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maVt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("matKhau")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("tenDn")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maNg");

                    b.HasIndex("maVt");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Be_e_learning.Model.NoiDung", b =>
                {
                    b.Property<string>("maNd")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maCh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maLoaiNd")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("moTa")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("stt")
                        .HasColumnType("int");

                    b.Property<string>("tieuDe")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("maNd");

                    b.HasIndex("maCh");

                    b.HasIndex("maLoaiNd");

                    b.ToTable("NoiDung");
                });

            modelBuilder.Entity("Be_e_learning.Model.VaiTro", b =>
                {
                    b.Property<string>("maVt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tenVt")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("maVt");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("Be_e_learning.Model.Video", b =>
                {
                    b.Property<string>("maVideo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("maNd")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("video")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("maVideo");

                    b.HasIndex("maNd")
                        .IsUnique()
                        .HasFilter("[maNd] IS NOT NULL");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Be_e_learning.Model.ChuongKhoaHoc", b =>
                {
                    b.HasOne("Be_e_learning.Model.KhoaHoc", "khoaHoc")
                        .WithMany("chuongKhoaHocs")
                        .HasForeignKey("maKh")
                        .HasConstraintName("FK_ChuongKhoaHoc_khoaHoc");

                    b.Navigation("khoaHoc");
                });

            modelBuilder.Entity("Be_e_learning.Model.GiangVien", b =>
                {
                    b.HasOne("Be_e_learning.Model.NguoiDung", "nguoiDung")
                        .WithMany("giangViens")
                        .HasForeignKey("maNg")
                        .HasConstraintName("FK_giangVien_nguoiDung");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("Be_e_learning.Model.KhoaHoc", b =>
                {
                    b.HasOne("Be_e_learning.Model.DanhMuc", "danhMuc")
                        .WithMany("khoaHocs")
                        .HasForeignKey("maDm")
                        .HasConstraintName("FK_khoaHoc_danhmuc");

                    b.HasOne("Be_e_learning.Model.GiangVien", "giangVien")
                        .WithMany("khoaHocs")
                        .HasForeignKey("maGv")
                        .HasConstraintName("FK_khoaHoc_giangVien");

                    b.Navigation("danhMuc");

                    b.Navigation("giangVien");
                });

            modelBuilder.Entity("Be_e_learning.Model.NguoiDung", b =>
                {
                    b.HasOne("Be_e_learning.Model.VaiTro", "vaiTro")
                        .WithMany("nguoiDungs")
                        .HasForeignKey("maVt")
                        .HasConstraintName("FK_nguoiDung_vaiTro");

                    b.Navigation("vaiTro");
                });

            modelBuilder.Entity("Be_e_learning.Model.NoiDung", b =>
                {
                    b.HasOne("Be_e_learning.Model.ChuongKhoaHoc", "chuongKhoaHoc")
                        .WithMany("noiDungs")
                        .HasForeignKey("maCh")
                        .HasConstraintName("FK_Noidung_ChuongKhoaHoc");

                    b.HasOne("Be_e_learning.Model.LoaiNoiDung", "loaiNoiDung")
                        .WithMany("noiDungs")
                        .HasForeignKey("maLoaiNd")
                        .HasConstraintName("FK_Noidung_LoaiNoiDung");

                    b.Navigation("chuongKhoaHoc");

                    b.Navigation("loaiNoiDung");
                });

            modelBuilder.Entity("Be_e_learning.Model.Video", b =>
                {
                    b.HasOne("Be_e_learning.Model.NoiDung", "noidung")
                        .WithOne("video")
                        .HasForeignKey("Be_e_learning.Model.Video", "maNd")
                        .HasConstraintName("FK_Video_NoiDung");

                    b.Navigation("noidung");
                });

            modelBuilder.Entity("Be_e_learning.Model.ChuongKhoaHoc", b =>
                {
                    b.Navigation("noiDungs");
                });

            modelBuilder.Entity("Be_e_learning.Model.DanhMuc", b =>
                {
                    b.Navigation("khoaHocs");
                });

            modelBuilder.Entity("Be_e_learning.Model.GiangVien", b =>
                {
                    b.Navigation("khoaHocs");
                });

            modelBuilder.Entity("Be_e_learning.Model.KhoaHoc", b =>
                {
                    b.Navigation("chuongKhoaHocs");
                });

            modelBuilder.Entity("Be_e_learning.Model.LoaiNoiDung", b =>
                {
                    b.Navigation("noiDungs");
                });

            modelBuilder.Entity("Be_e_learning.Model.NguoiDung", b =>
                {
                    b.Navigation("giangViens");
                });

            modelBuilder.Entity("Be_e_learning.Model.NoiDung", b =>
                {
                    b.Navigation("video");
                });

            modelBuilder.Entity("Be_e_learning.Model.VaiTro", b =>
                {
                    b.Navigation("nguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
